### ISSUE TITLE
Stack level too deep error

### ISSUE THREAD

**Issue by kxu1988** [Dimkarodinz/activeadmin_ancestry_view#1]
- I create a model 'User', which  have  has_ancestry.
- when enter the index page of User , it happened an list of errors "Stack level too deep error" 
- ruby version is 2.5.1
- Rails 5.2
- Below is my code:

```
ActiveAdmin.register User do
  ancestry_view(:index) do
  end

  ancestry_view(:show) do
  end

  ancestry_view :index,
     headers: {
       title: '123', 
       info: 'Info',                       # 'Info' link name
       expand: 'Expand',                   # 'Expand' link name
    },
    table: {
      'Name' => :first_name,     # Key - any string or symbol, value - model instance method.
       :email => :email           # Table, as well as 'Info' and 'Expand' links,
    },                           # shows only if :table has values.

    no_childless_link: true,     # Hide link to #show for childless nodes. Default is false
    no_color: true,              # On/off color nodes. Default is false
    shift_depth: 4               # In 'parrots'; looks good if >= 3. Default is 4
end
```

**Comment by leoc** [comment]
I have the same error. Did you find a work-around yet, @kxu1988 ?

**Comment by leoc** [comment]
I just installed `slim-rails` and it seems to work now.

**Comment by NanoMeko** [comment]
Same issue

**Comment by kimroen** [comment]
Same here. The templates are written using slim, and it doesn't add this support itself.

**Comment by Dimkarodinz** [comment]
Moved `slim-rails` from development dependencies to main ones for next version.
And guys, please make sure you include only ONE `ancestry_view` per action (index or view). Two equal action will lead to recursion and 'stack level too deep error'.

This will create recursion, please try to avoid:
```ruby
ancestry_view(:index)
ancestry_view :index
```
